### PR TITLE
[change] adjust Debian package to usage of Flyway

### PR DESCRIPTION
**Pull request by tkrille**
I tried to remove all SQL init stuff regarding the auth- and resource-server. Dunno much about the Debian package magic behind it. @smancke @tpick I really need your feedback on this!

### CODE REVIEW

**Comment by tkrille** [comment]
So far I can tell that the packages are working. One last issue is, that you don't get asked for the database user and password anymore. @smancke @tpick any ideas how to bring this back?

**Comment by timopick** [comment]
I guess it is because you have removed the dbc_go command, which triggers the database configuration dialog and updates the dbc_dbuser, dbc_dbname and dbc_dbpass variables.

**Comment by tkrille** [comment]
> May also be removed? 
> Also the next two lines ..

@smancke which lines exactly?

@tpick is there are a substitute for `dbc_go` that still asks for the database connection parameters, but does not run any SQL scripts?

Anyways, if it's ok that the packages don't ask for database connection parameters anymore, then we will use this version as is.

**Comment by tkrille** [comment]
@smancke sorry, the overview did not show the lines to me you commented on. It's clear to me now. And yes, I think they can be removed, but wasn't sure :) So, I will remove these lines too.

**Comment by timopick** [comment]
@tkrille `dbc_go` runs the scripts in `/usr/share/dbconfig-common/data/<dbconfig_module>/install/<dbname>` (here: /usr/share/dbconfig-common/data/osiam-auth-server/install/pgsql). If no file is present, dbconfig should not run the script, but still ask for the db/user/pass.

**Comment by tkrille** [comment]
@tpick Yes, that might do the trick. But before making further efforts, we should decide whether it's ok or not, when the op doesn't get asked about the database connection parameters on installation. afaik they (the op) have to change the configuration anyway, because most set URLs point to localhost, which might not always be the right thing.

so, in that spirit, I vote for "don't ask on installation"

**Comment by timopick** [comment]
@tkrille that's fine for me

**Comment by tkrille** [comment]
alright, so this can be merged now @dacrome

**Comment by tkrille** [comment]
ok, lets wait until the releases have been build.

**Comment by tkrille** [comment]
ready to merge!

**Pull request merged**
