### PR TITLE
OSIAM 3.0

### PR DESCRIPTION
**Pull request by dacrome**

### CODE REVIEW

**Comment by dacrome** [comment]
Blocked by https://github.com/osiam/osiam/pull/44

**Comment by tkrille** [comment]
Shouldn't we do this not until the stuff is released?

**Comment by dacrome** [comment]
> Shouldn't we do this not until the stuff is released?

Sure, this is just a proposal and that's why I posted [this comment](https://github.com/osiam/distribution/pull/37#issuecomment-150251582)

**Comment by tkrille** [comment]
I don't think we should support the big distribution with 3.0 anymore. Everything is contained in the WAR now anyway.

**Pull request closed without merging**
